apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "hematite.fullname" . }}
  labels:
    {{- include "hematite.labels" . | nindent 4 }}
data:
  hematite.yaml: |
    {{- .Values.config | nindent 4 }}
