apiVersion: v1
kind: Service
metadata:
  name: {{ include "hematite.fullname" . }}
  labels:
    {{- include "hematite.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  {{- if .Values.service.clusterIP }}
  clusterIP: {{ .Values.service.clusterIP }}
  {{- end }}
  selector:
    {{- include "hematite.selectorLabels" . | nindent 4 }}
  ports:
    {{- if .Values.service.dns.enabled }}
    - name: dns
      port: {{ .Values.service.dns.port }}
      targetPort: {{ .Values.service.dns.port }}
      protocol: UDP
    {{- end }}
    {{- if .Values.service.http.enabled }}
    - name: http
      port: {{ .Values.service.http.port }}
      targetPort: {{ .Values.service.http.port }}
    {{- end }}
    {{- if .Values.service.https.enabled }}
    - name: https
      port: {{ .Values.service.https.port }}
      targetPort: {{ .Values.service.https.port }}
    {{- end }}
    {{- if .Values.service.tunnel.enabled }}
    - name: tunnel
      port: {{ .Values.service.tunnel.port }}
      targetPort: {{ .Values.service.tunnel.port }}
    {{- end }}
    {{- if .Values.service.management.enabled }}
    - name: management
      port: {{ .Values.service.management.port }}
      targetPort: {{ .Values.service.management.port }}
    {{- end }}
